create table CRE_CONSEJO_DIRECTIVO
(
  id                         NUMBER(10),
  des_nombres               VARCHAR2(200),
  des_apellidos             VARCHAR2(200),
  des_dni                   VARCHAR2(200),
  des_cargo                 VARCHAR2(200),
  des_edad                  VARCHAR2(200),
  des_email                 VARCHAR2(200),
  des_codigo_asociacion     VARCHAR2(200)
 
)
delete from CRE_CONSEJO_DIRECTIVO
drop table CRE_CONSEJO_DIRECTIVO

select *from CRE_CONSEJO_DIRECTIVO
create table CRE_DOCUMENTO_DETALLE
(
  id                           NUMBER(10),
  des_codigo_asociacion        VARCHAR2(200),
  des_version                  VARCHAR2(200),
  des_fecha_actualizacion      Date,
  des_fecha_documento          Date,
  des_link_documento_inscrito  VARCHAR2(200),
  des_fecha_inicio_vigencia    Date,
  des_fecha_fin_vigencia       Date,
  des_observaciones            VARCHAR2(200)
 
)
delete from CRE_DOCUMENTO_DETALLE

select *from CRE_DOCUMENTO_DETALLE
drop table CRE_DOCUMENTO_DETALLE

SELECT *
FROM ALL_SEQUENCES@prod;

select *from CRE_USUARIO


insert into CRE_USUARIO (des_usuario,cod_empresa,cod_estado,fec_registro,des_password,Des_Codigo_Asociacion)
  values ('JDELACRUZR','001',1,sysdate,'','E00241');
  
  
  create table CRE_PROPIETARIOS
(   id_propietario               NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY, 
    des_codigo_propietario       VARCHAR2(200),
    des_codigo_Dni               VARCHAR2(200),
    des_Apellidos                VARCHAR2(200),
    des_estado_civil             VARCHAR2(200),
    des_nombres                  VARCHAR2(200),
    des_dni_conyugue             VARCHAR2(200),
    num_telefono                 NUMBER(30),
    des_correo                   VARCHAR2(200),
    des_documento_link           VARCHAR2(200),
    des_codigo_asociacion        VARCHAR2(200),
    des_estado                   VARCHAR2(100)
)

alter table CRE_PROPIETARIOS
  add constraint CRE_PROPIETARIOS_PK primary key (id_propietario);
  
drop table CRE_PROPIETARIOS
select *from CRE_PROPIETARIOS


alter table CRE_PROPIETARIOS
  add des_estado VARCHAR2(100);
  
  
create table CRE_INMUEBLE_PROP
( 
    
  id_inmueble                  NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY, 
  num_partida_registral        VARCHAR2(200),
  des_tipo_dominio             VARCHAR2(200),
  des_direccion                VARCHAR2(200),
  des_oficina_registral        VARCHAR2(200),
  num_acciones_derechos        NUMBER(10),
  des_departamento             VARCHAR2(200),
  num_area                      NUMBER(10),
  des_provincia                VARCHAR2(200),
  des_codigo_asociacion        VARCHAR2(200)
 
)

alter table CRE_INMUEBLE_PROP
  add constraint CRE_INMUEBLE_PROP_PK primary key (id_inmueble);
  
drop table CRE_INMUEBLE_PROP

-- select prop inmueble
select * from CRE_INMUEBLE_PROP
delete from CRE_INMUEBLE_PROP

select * from CRE_PROPIETARIOS


select *from  CRE_PROPIETARIOS_INMUEBLE

--delete  prop inmueble
delete from CRE_PROPIETARIOS_INMUEBLE
delete from CRE_PROPIETARIOS
delete from CRE_INMUEBLE_PROP

CREATE TABLE CRE_PROPIETARIOS_INMUEBLE (
    id_propietario NUMBER REFERENCES CRE_PROPIETARIOS(id_propietario),
    id_inmueble NUMBER REFERENCES CRE_INMUEBLE_PROP(id_inmueble),
    PRIMARY KEY (id_propietario, id_inmueble)
);

drop table CRE_PROPIETARIOS_INMUEBLE

-- Create table
create table CRE_EXPEDIENTE_PROPIETARIO
(
  des_nombres                     NUMBER(10),
  des_apellido_materno            VARCHAR2(200),
  des_apellido_paterno            VARCHAR2(200),
  des_dni                         VARCHAR2(200),
  des_cargo                       VARCHAR2(200),
  des_edad                        VARCHAR2(200),
  des_email                       VARCHAR2(200),
  des_genero                      VARCHAR2(200),
  fec_fecha_nacimiento            VARCHAR2(200),
  des_departamento_nacimiento     VARCHAR2(200),
  des_grado_instruccion           VARCHAR2(200),
  des_estado_civil                VARCHAR2(200),
  des_departamento_dom            VARCHAR2(200),
  des_provincia_dom               VARCHAR2(200),
  des_distrito_dom                VARCHAR2(200),
  des_direccion_dom               VARCHAR2(200),
  des_telefono                    VARCHAR2(50),
  des_correo_electronico          VARCHAR2(200)    


)

delete  from CRE_EXPEDIENTE_PROPIETARIO
select *from CRE_EXPEDIENTE_PROPIETARIO


-- Create table
create table CRE_PROPIETARIO_BAJA_DET
(
  id_baja_det                     NUMBER(20) GENERATED BY DEFAULT ON NULL AS IDENTITY, 
  des_codigo_propietario          VARCHAR2(200),
  des_motivo                      VARCHAR2(200),
  fec_baja                        VARCHAR2(200),
  des_obserbaciones               VARCHAR2(200),
  des_link_documento              VARCHAR2(200)
 
)
drop table CRE_PROPIETARIO_BAJA_DET

select *from CRE_PROPIETARIO_BAJA_DET

select * from APP_BALANCE_GENERAL

  PROCEDURE SP_GET_BALANCE_GNRAL_XDNI(P_USUARIO        IN VARCHAR2,
                                 PI_NUM_DOCUMENTO IN VARCHAR2,
                                 CURSOR1          OUT SYS_REFCURSOR,
                                 P_ERROR          OUT INTEGER,
                                 P_MENSAJE        OUT VARCHAR2);  
                                 


PROCEDURE SP_GET_BALANCE_GNRAL_XDNI (
        P_USUARIO           IN  VARCHAR2,
        PI_NUM_DOCUMENTO    IN  VARCHAR2,
        CURSOR1             OUT SYS_REFCURSOR,
        P_ERROR             OUT INTEGER,
        P_MENSAJE           OUT VARCHAR2
    ) AS
        V_COD_EMPRESA VARCHAR2(4) := '';
        V_IND_SUPERV VARCHAR2(1) := '';
        V_TIPO_USUARIO VARCHAR2(3) := '';
        V_COD_CLI VARCHAR2(50) := '';
        V_COD_TIP_DOC VARCHAR2(2) := '';
    BEGIN
        P_ERROR := 0;
        P_MENSAJE := '';
        V_COD_TIP_DOC := '1'; --CODIGO TIPO DOCUMENTO
        SELECT NVL(E.COD_EMPRESA, '') INTO V_COD_EMPRESA
           FROM MAE_EMPRESAS E
               WHERE E.IND_BAJA = 'N';
 
            SELECT NVL(F.IND_PERFIL_SUP_HR_MOVIL, '') INTO V_IND_SUPERV FROM MAE_USUARIO_EMP A
             INNER JOIN MAE_PERFIL F ON F.COD_PERFIL = A.COD_PERFIL
             INNER JOIN MAE_USUARIO B ON A.COD_USUARIO = B.COD_USUARIO
                 WHERE B.IND_BAJA = 'N' AND (F.IND_BAJA = 'N' OR F.IND_BAJA IS NULL) AND
                       A.COD_USUARIO = UPPER(P_USUARIO);
            IF V_IND_SUPERV = 'N' THEN
               V_TIPO_USUARIO := 'EDN';
            ELSE
               V_TIPO_USUARIO := 'SUP';
            END IF;
            OPEN CURSOR1 FOR
            SELECT ACT_DISP_CAJA, ACT_DISP_BANCO, ACT_INV_MERCADERIAS, ACT_INV_PROVISIONES, ACT_ADE_PROVEEDORES,
                   ACT_FIJO_MAQ_EQ, ACT_FIJO_INMUEBLES, ACT_FIJO_DEPREC, ACT_XC_HASTA_30D, ACT_XC_MAYOR_30D,
                   ACT_XC_PROVISIONES, ACT_OTROS, PASV_XP_HASTA_30D, PASV_XP_MAYOR_30D, PASV_PRST_D_HASTA_1,
                   PASV_PRST_D_MAYOR_1, PASV_AD_CLIENTES, PASV_OTR_CU_PAG, PATR_CAPITAL, PATR_RES_EJERCICIO
            FROM   APP_BALANCE_GENERAL
            WHERE  NUM_DOCUMENTO = PI_NUM_DOCUMENTO AND COD_EMPRESA = V_COD_EMPRESA  ORDER BY FEC_REGISTRO DESC FETCH FIRST 1 ROW ONLY
           
    EXCEPTION WHEN OTHERS THEN
        P_ERROR := 1;
        P_MENSAJE := SQLERRM;
    END;

-----

select * from APP_BALANCE_GENERAL

 SELECT NUM_DOCUMENTO, NUM_EVALUACION,ACT_DISP_CAJA, ACT_DISP_BANCO, ACT_INV_MERCADERIAS, ACT_INV_PROVISIONES, ACT_ADE_PROVEEDORES,
                   ACT_FIJO_MAQ_EQ, ACT_FIJO_INMUEBLES, ACT_FIJO_DEPREC, ACT_XC_HASTA_30D, ACT_XC_MAYOR_30D,
                   ACT_XC_PROVISIONES, ACT_OTROS, PASV_XP_HASTA_30D, PASV_XP_MAYOR_30D, PASV_PRST_D_HASTA_1,
                   PASV_PRST_D_MAYOR_1, PASV_AD_CLIENTES, PASV_OTR_CU_PAG, PATR_CAPITAL, PATR_RES_EJERCICIO,FEC_REGISTRO
            FROM   APP_BALANCE_GENERAL
            WHERE  NUM_DOCUMENTO = '40969023' AND COD_EMPRESA = '0001'   ORDER BY FEC_REGISTRO DESC FETCH FIRST 1 ROW ONLY; 
            
           
 select *from  CRE_INF_SOCIO_ECONOMICA;
 
 PROCEDURE SP_SET_BALANCE_GNRAL (
        P_USUARIO               IN  VARCHAR2,
        PI_NUM_DOCUMENTO        IN  VARCHAR2,
        PI_NUM_EVAL             IN  VARCHAR2,
        P_CAJAS                 IN  NUMBER,
        P_BANCOS                IN  NUMBER,
        P_IMP_MERC_INS          IN  NUMBER,
        P_INV_PROVISIONES       IN  NUMBER,
        P_ADE_PROVEEDORES       IN  NUMBER,
        P_MAQ_EQUIPO            IN  NUMBER,
        P_INMUEBLES             IN  NUMBER,
        P_ACTV_DEPRECIACION     IN  NUMBER,
        P_CXC_HASTA_30DIAS      IN  NUMBER,
        P_CXC_MAYOR_30DIAS      IN  NUMBER,
        P_CXC_PROVISIONES       IN  NUMBER,
        P_ACTV_OTROS            IN  NUMBER,
        P_CXP_HASTA_30DIAS      IN  NUMBER,
        P_CXP_MAYOR_30DIAS      IN  NUMBER,
        P_DEUDA_HASTA_1         IN  NUMBER,
        P_DEUDA_MAYOR_1         IN  NUMBER,
        P_ADE_CLIENTES          IN  NUMBER,
        P_OTRAS_CXP             IN  NUMBER,
        P_CAPITAL               IN  NUMBER,
        P_RESULT_EJERCICIO      IN  NUMBER,
        P_ERROR                 OUT VARCHAR2,
        P_MENSAJE               OUT VARCHAR2
    ) AS
        V_COD_EMPRESA VARCHAR2(4) := '';
        V_COD_SUCURSAL VARCHAR2(3) := '';
        V_COD_AGENCIA VARCHAR2(3) := '';
        V_COD_CLI VARCHAR2(50) := '';
        V_IMP_DISPONIBLE NUMBER(14,4) := 0;
        V_IMP_INVENTARIO NUMBER(14,4) := 0;
        V_IMP_ACTIVO_FIJO NUMBER(14,4) := 0;
        V_IMP_CTA_X_COBRAR NUMBER(14,4) := 0;
        V_IMP_TOT_ACTIVO NUMBER(14,4) := 0;
        V_IMP_CTA_X_PAGAR NUMBER(14,4) := 0;
        V_IMP_PRESTAMOS NUMBER(14,4) := 0;
        V_IMP_TOT_PASIVO NUMBER(14,4) := 0;
        V_TOT_PATRIMONIO NUMBER(14,4) := 0.0;
        V_NUM_EVALUACION_ANT INTEGER := 0;
        V_NUM_EVALUACION INTEGER := 0;
        V_NUM_EVALUACION_APP INTEGER := 0;
        V_TIP_USUARIO VARCHAR2(3) := '';
        V_COUNT_EDN INTEGER := 0;
        V_COUNT_EDN_APP INTEGER := 0;
        V_COUNT_SUP INTEGER := 0;
        V_COUNT_SUP_APP INTEGER := 0;
        CONST_COD_MONEDA CONSTANT VARCHAR2(2):= '01';
        V_COD_TIP_DOC VARCHAR2(2) := '';
    BEGIN
        P_ERROR := 0;
        P_MENSAJE := '';
        V_IMP_DISPONIBLE := P_CAJAS + P_BANCOS;
        V_IMP_INVENTARIO := P_IMP_MERC_INS - P_INV_PROVISIONES;
        V_IMP_ACTIVO_FIJO := P_MAQ_EQUIPO + P_INMUEBLES - P_ACTV_DEPRECIACION;
        V_IMP_CTA_X_COBRAR := P_CXC_HASTA_30DIAS + P_CXC_MAYOR_30DIAS - P_CXC_PROVISIONES;
        V_IMP_TOT_ACTIVO := V_IMP_DISPONIBLE + P_ADE_PROVEEDORES + V_IMP_INVENTARIO + V_IMP_ACTIVO_FIJO + V_IMP_CTA_X_COBRAR + P_ACTV_OTROS;
        V_IMP_CTA_X_PAGAR := P_CXP_HASTA_30DIAS + P_CXP_MAYOR_30DIAS;
        V_IMP_PRESTAMOS := P_DEUDA_HASTA_1 + P_DEUDA_MAYOR_1;
        V_IMP_TOT_PASIVO := V_IMP_CTA_X_PAGAR + V_IMP_PRESTAMOS + P_ADE_CLIENTES + P_OTRAS_CXP;
        V_TOT_PATRIMONIO := V_IMP_TOT_ACTIVO - V_IMP_TOT_PASIVO;
  
        UPDATE APP_BALANCE_GENERAL SET
                    ACT_DISP_CAJA = P_CAJAS, ACT_DISP_BANCO = P_BANCOS, ACT_DISP_SUBTOTAL = V_IMP_DISPONIBLE, ACT_INV_MERCADERIAS = P_IMP_MERC_INS,
                    ACT_INV_PROVISIONES = P_INV_PROVISIONES, ACT_INV_SUBTOTAL = V_IMP_INVENTARIO, ACT_ADE_PROVEEDORES = P_ADE_PROVEEDORES, ACT_FIJO_MAQ_EQ = P_MAQ_EQUIPO,
                    ACT_FIJO_INMUEBLES = P_INMUEBLES, ACT_FIJO_DEPREC = P_ACTV_DEPRECIACION, ACT_FIJO_SUBTOTAL = V_IMP_ACTIVO_FIJO, ACT_XC_HASTA_30D = P_CXC_HASTA_30DIAS,
                    ACT_XC_MAYOR_30D = P_CXC_MAYOR_30DIAS, ACT_XC_PROVISIONES = P_CXC_PROVISIONES, ACT_XCOBRAR_SUBTOTAL = V_IMP_CTA_X_COBRAR, ACT_OTROS = P_ACTV_OTROS,
                    ACT_SUBTOTAL = V_IMP_TOT_ACTIVO, PASV_XP_HASTA_30D = P_CXP_HASTA_30DIAS, PASV_XP_MAYOR_30D = P_CXP_MAYOR_30DIAS, PASV_XPAGAR_SUBTOTAL = V_IMP_CTA_X_PAGAR,
                    PASV_PRST_D_HASTA_1 = P_DEUDA_HASTA_1, PASV_PRST_D_MAYOR_1 = P_DEUDA_MAYOR_1, PASV_PRESTAMO_SUBTOTAL = V_IMP_PRESTAMOS, PASV_AD_CLIENTES = P_ADE_CLIENTES,
                    PASV_OTR_CU_PAG = P_OTRAS_CXP, PASV_SUBTOTAL = V_IMP_TOT_PASIVO, PATR_CAPITAL = P_CAPITAL, PATR_RES_EJERCICIO = P_RESULT_EJERCICIO,
                    PATR_SUBTOTAL = V_TOT_PATRIMONIO, COD_USUARIO_MOD = UPPER(P_USUARIO), FEC_MODIFICACION = SYSDATE
        WHERE NUM_DOCUMENTO = PI_NUM_DOCUMENTO AND COD_EMPRESA = V_COD_EMPRESA AND NUM_EVALUACION = PI_NUM_EVAL ;
              P_MENSAJE := 'Registro Exitoso';
       
    EXCEPTION WHEN OTHERS THEN
        P_ERROR := SQLCODE;
        P_MENSAJE := SQLERRM;
        DBMS_OUTPUT.PUT_LINE('error ' || SQLCODE || '- ' || SQLERRM);
        
        
    END;
    
-- Create table documento propietario
create table CRE_DOCUMENTO_PROPIETARIO
( 
  num_documento_prop           NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
  des_link_documento           VARCHAR2(200),
  des_dni                      VARCHAR2(200),
  des_codigo_asoc              VARCHAR2(200),
  des_tipo_doc                  VARCHAR2(200),
  fec_timestamp_call           DATE
 
)

select *from CRE_DOCUMENTO_PROPIETARIO

drop table CRE_DOCUMENTO_PROPIETARIO

select *from APP_FOTO_CLI_PROSPECTO where num_doc_ide='74931915'
